### ISSUE TITLE
Jupyter Book - Not Building 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-intro.zh-cn#112]
I am having issues building the lectures

Here is some of the output that is being displayed

```bash
Extension error:
Could not import extension sphinxext.rediraffe (exception: No module named 'sphinxext')
Traceback (most recent call last):
  File "/Users/mmcky/anaconda3/lib/python3.11/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmcky/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mmcky** [comment]
@mmcky do you have time to look at this?
